import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Listing from '../components/Listing';
import Connect from '../components/Connect';
import { useState, useEffect } from 'react';

export default function Home() {
  const [showListings, setShowListings] = useState(false);

  useEffect(() => {
    setShowListings(true);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Marketplace - Next example</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href='https://docs.manifold.xyz/v/manifold-for-developers/client-widgets/overview'>
            Manifold
          </a>
          <span> </span>
          Next.js Template
        </h1>
        <br />

        {/* -- Add Connect Widget -- */}
        <Connect network={process.env.NEXT_APP_NETWORK} />

        {/* ~~ Add Marketplace Widget component ~~ */}
        <Listing
          id={5155}
          // network={process.env.NEXT_APP_NETWORK}
          // id={'4250'}
          network={'1'}
        />
      </main>
    </div>
  );
}
